services:
  broker:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=broker
  order-service:
    image: sample-spring-kafka-microservices/order-service:1.0-SNAPSHOT
    ports:
      - "8080"
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  payment-service:
    image: sample-spring-kafka-microservices/payment-service:1.0-SNAPSHOT
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  stock-service:
    image: sample-spring-kafka-microservices/stock-service:1.0-SNAPSHOT
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  dashboard-service:
    image: sample-spring-kafka-microservices/dashboard-service:1.0-SNAPSHOT
    ports:
      - "8081:8081"
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8888:8080"
    depends_on:
      - broker
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: wizard_test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
    links:
      - broker

